### ISSUE TITLE
Folder structure 

### ISSUE THREAD

**Issue by shirivo** [MicrosoftDocs/ai-fundamentals#4]
In the text analytics notebook, this is the code:

![general](https://user-images.githubusercontent.com/620849/89369055-49d19100-d69a-11ea-8da5-d4a0ac2be89f.jpeg)

The issue is that sample is in a different path that expected.

![draw](https://user-images.githubusercontent.com/620849/89369054-4938fa80-d69a-11ea-8d18-2d4375dd45d0.jpeg)

**Comment by stevenhm88** [comment]
I have the same Issue

**Comment by GraemeMalcolm** [comment]
You need to have run the previous cells to initialize the reviews variable (the code to do that is in the very first cell of the notebook)
