### ISSUE TITLE
The method used to create the "cog_region" variable no longer gives the right result

### ISSUE THREAD

**Issue by davidokeyode** [MicrosoftDocs/ai-fundamentals#5]
**File**: 02b - Speech.ipynb
**Link**: https://github.com/MicrosoftDocs/ai-fundamentals/blob/master/02b%20-%20Speech.ipynb
**Issue Description**: found in "Line 49"

  "cog_region = cog_endpoint[8:cog_endpoint.find('.')]\n",

For new cognitive service resources, this variable returns the name and not the region of the resource which leads to "SpeechRecognitionResult(result_id=**************, text="", reason=ResultReason.Canceled) later down the line

Worked around by statically entering the region of the resource

**Comment by GraemeMalcolm** [comment]
Thanks @davidokeyode - fixed!
