### ISSUE TITLE
Instructions in "Create an Entity" section no longer accurate

### ISSUE THREAD

**Issue by davidokeyode** [MicrosoftDocs/ai-fundamentals#6]
**File**: 02d - Language Understanding.ipynb
**Link**: https://github.com/MicrosoftDocs/ai-fundamentals/blob/master/02d%20-%20Language%20Understanding.ipynb
**Issue Description**: Step numbers 2 to 5 in the "Create an Entity" section no longer accurate. It seems as if the resource only accepts JSON input and no manual input now

**Comment by sherzyang** [comment]
Thanks @davidokeyode for letting us know. It's been patched.
